version: "3.8"

services:
  postgres:
    env_file: .env
    image: postgres:14.3
    container_name: blog-api-container
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - ${DB_PORT}:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
